### ISSUE TITLE
WebSocket connection to 'ws://127.0.0.1:7778/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by umairali** [assertchris-tutorials/laravel-4-real-time-chat#11]
Hi

i am facing this issue in browser please suggest any thing 

WebSocket connection to 'ws://127.0.0.1:7778/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by yesman0319** [comment]
看不懂 - -||

**Comment by stevengpn** [comment]
make sure the server listening IP is  **0.0.0.0** instead of 127.0.0.1

**Comment by hugoofab** [comment]
maybe yesman0319 brings the definitive response but, someone can read it?

**Comment by kairat-beep** [comment]
i can't understand what i see- translating explicitly." with some  <- -||> i have no idea what is that"

**Comment by assertchris** [comment]
Folks, this is an old issue, and an even older tutorial. If you would like to discuss [over twitter](https://twitter.com/assertchris) (and with a link to some code you are working on at the time), then I can help try to debug there. In the meantime, I'm going to lock this thread.
